name: Deploy to Amazon ECS

on:
  push:
    branches:
      - 'prod'

env:
  AWS_REGION: ap-northeast-2
  NEST_ECR_REPOSITORY: oncare
  PYTHON_ECR_REPOSITORY: oncare-python
  ECS_NEST_SERVICE: oncare-service
  ECS_PYTHON_SERVICE: oncare-service-lrkflr0l
  ECS_CLUSTER: oncare
  ECS_TASK_DEFINITION: .aws/task-definition.json
  NEST_CONTAINER_NAME: oncare
  PYTHON_CONTAINER_NAME: whisper
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push NestJS image
        id: build-nest-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
        run: |
          docker build --no-cache -f ./Dockerfile.nest -t $ECR_REGISTRY/${{ env.NEST_ECR_REPOSITORY }}:$IMAGE_TAG .
          docker push $ECR_REGISTRY/${{ env.NEST_ECR_REPOSITORY }}:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/${{ env.NEST_ECR_REPOSITORY }}:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Build, tag, and push FastAPI image
        id: build-python-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
        run: |
          docker build -f ./Dockerfile.python -t $ECR_REGISTRY/${{ env.PYTHON_ECR_REPOSITORY }}:$IMAGE_TAG .
          docker push $ECR_REGISTRY/${{ env.PYTHON_ECR_REPOSITORY }}:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/${{ env.PYTHON_ECR_REPOSITORY }}:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Render NestJS container in task definition
        id: render-nest
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          container-name: ${{ env.NEST_CONTAINER_NAME }}
          image: ${{ steps.build-nest-image.outputs.image }}
          environment-variables: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}
            AWS_REGION=${{ env.AWS_REGION }}

      - name: Render Python container in task definition
        id: render-python
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ steps.render-nest.outputs.task-definition }}
          container-name: ${{ env.PYTHON_CONTAINER_NAME }}
          image: ${{ steps.build-python-image.outputs.image }}
          environment-variables: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}
            AWS_REGION=${{ env.AWS_REGION }}

      - name: Deploy to oncare-service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-python.outputs.task-definition }}
          service: ${{ env.ECS_NEST_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true

      - name: Deploy to python-service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-python.outputs.task-definition }}
          service: ${{ env.ECS_PYTHON_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
